# Generated by Django 5.0.2 on 2024-02-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("app", models.CharField(blank=True, max_length=120, null=True)),
                ("model", models.CharField(blank=True, max_length=120, null=True)),
                ("lables", models.TextField(blank=True, null=True)),
                ("object_count", models.IntegerField(default=0)),
                (
                    "csvfile",
                    models.FileField(blank=True, null=True, upload_to="datasets/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
