# Generated by Django 5.0.2 on 2024-02-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPUInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("frequency", models.FloatField()),
                ("arch", models.CharField(max_length=10)),
                ("bits", models.IntegerField()),
                ("count", models.IntegerField()),
                ("l1_data_cache_size", models.IntegerField(null=True)),
                ("l1_instruction_cache_size", models.IntegerField(null=True)),
                ("l2_cache_size", models.IntegerField()),
                ("l2_cache_line_size", models.IntegerField()),
                ("l2_cache_associativity", models.IntegerField()),
                ("l3_cache_size", models.IntegerField(null=True)),
                ("stepping", models.IntegerField()),
                ("model", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GPUInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("memory", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CPUMonitoringModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency_actual", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.cpuinfomodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComputerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.cpuinfomodel",
                    ),
                ),
                (
                    "gpu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hardware.gpuinfomodel",
                    ),
                ),
            ],
        ),
    ]
